biblioteca/urls.py
from django.urls import path, include
from rest_framework import routers
from biblioteca import views

router = routers.DefaultRouter()
# router.register(r'nacionalidades', views.NacionalidadViewSet,basename='nacionalidades')    
router.register(r'autores', views.AutorViewSet, basename='autores')
router.register(r'comunas', views.ComunaViewSet, basename='comunas')
router.register(r'direcciones', views.DireccionViewSet, basename='direcciones')
router.register(r'bibliotecas', views.BibliotecaViewSet,basename='bibliotecas')
router.register(r'lectores', views.LectorViewSet, basename='lectores')
router.register(r'tipos-categorias', views.TipoCategoriaViewSet,basename='tipos-categorias')
router.register(r'categorias', views.CategoriaViewSet, basename='categorias')
router.register(r'libros', views.LibroViewSet, basename='libros')
router.register(r'prestamos', views.PrestamoViewSet, basename='prestamos')
router.register(r'reservas',views.ReservaViewSet,basename='reservas')
router.register(r'tipos-parametros', views.TipoParametroViewSet,basename='tipos-parametros')
router.register(r'parametros', views.ParametroViewSet, basename='parametros')

urlpatterns = [
    path('', include(router.urls))
]

drf/urls.py
from biblioteca import views
from django.contrib import admin
from django.urls import path, include
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib.auth import views as auth_views

schema_view = get_schema_view(
    openapi.Info(
        title="Documentación API Gestión de Biblioteca",
        default_version='v1',
        description="Aplicación de Gestión de Biblioteca",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mi_correo@test.test"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.pagina_inicio, name='pagina_inicio'),
    path('biblioteca/', include('biblioteca.urls')),

    # URL's vistas de lista
    path('lista_nacionalidades', views.NacionalidadListView.as_view()),
    path('crear_nacionalidad', views.NacionalidadCreateView.as_view()),
    path('listado_autores', views.listado_autores,name='listado_autores'),
    path('listado_comunas', views.listado_comunas,name='listado_comunas'),
    path('listado_lectores', views.listado_lectores,name='listado_lectores'),
    path('listado_libros', views.listado_libros,name='listado_libros'),

    # URL's para documentación de API
    path('apidocs/', schema_view.with_ui('swagger',cache_timeout=0), name='schema-swagger-ui'),
    path('redocs/', schema_view.with_ui('redoc',cache_timeout=0), name='schema-redoc'),

    # URL's de autenticación
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('registro/', views.registro, name='registro'),
]

biblioteca/models.py
from django.db import models
import datetime
from django.forms import ValidationError
from rut_chile import rut_chile

ahora = datetime.datetime.now

# Create your models here.


def validar_rut(rut):
    valido = rut_chile.is_valid_rut(rut)
    if valido == False:
        raise ValidationError('RUT inválido.')


def validar_mayoria_edad(fecha_nacimiento):
    fecha_actual = datetime.datetime.now()
    edad = fecha_actual.year - fecha_nacimiento.year
    if (fecha_actual.month, fecha_actual.day) < (fecha_nacimiento.month, fecha_nacimiento.day):
        edad -= 1
    if edad < 18:
        raise ValidationError('El lector debe ser mayor de edad.')


class Nacionalidad(models.Model):
    pais = models.CharField(max_length=50, null=False)
    nacionalidad = models.CharField(max_length=50, null=False)
    created_at = models.DateTimeField(default=ahora)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nacionalidad

class OpcionesGenero(models.TextChoices):
    MASCULINO = 'M'
    FEMENINO = 'F'


class Autor(models.Model):
    id_nacionalidad = models.ForeignKey(
        Nacionalidad, on_delete=models.CASCADE,null=True)
    nombre = models.CharField(max_length=250, null=False)
    pseudonimo = models.CharField(max_length=50, null=True)
    biografia = models.TextField(null=True)
    genero = models.CharField(max_length=1,choices=OpcionesGenero.choices,default=OpcionesGenero.MASCULINO)
    imagen_autor = models.URLField(null=True)
    created_at = models.DateTimeField(default=ahora)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.pseudonimo:
            return self.pseudonimo
        else:
            return self.nombre


class Comuna(models.Model):
    codigo_comuna = models.CharField(max_length=5, null=False, unique=True)
    nombre_comuna = models.CharField(max_length=50, null=False)
    created_at = models.DateTimeField(default=ahora)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre_comuna


class Direccion(models.Model):
    id_comuna = models.ForeignKey(
        Comuna, on_delete=models.CASCADE, null=False)
    calle = models.CharField(max_length=50, null=False, default='')
    numero = models.CharField(max_length=10, null=False, default='')
    departamento = models.CharField(max_length=10, null=True)
    detalles = models.TextField(null=True)
    created_at = models.DateTimeField(default=ahora)
    updated_at = models.DateTimeField(auto_now=True)


class Biblioteca(models.Model):
    id_direccion = models.ForeignKey(
        Direccion, on_delete=models.CASCADE, null=True)
    nombre_biblioteca = models.CharField(max_length=100, null=False)
    web = models.CharField(max_length=255, null=True)
    habilitado = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=ahora)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre_biblioteca


class Lector(models.Model):
    id_biblioteca = models.ForeignKey(
        Biblioteca, on_delete=models.CASCADE, null=False)
    id_direccion = models.ForeignKey(
        Direccion, on_delete=models.CASCADE, null=True)
    rut_lector = models.CharField(
        max_length=12, null=False, unique=True, validators=[validar_rut])
    nombre_lector = models.CharField(max_length=255, null=False)
    correo_lector = models.CharField(max_length=255, null=True)
    fecha_nacimiento = models.DateField(
        null=True, default=None, validators=[validar_mayoria_edad])
    genero = models.CharField(max_length=1,choices=OpcionesGenero.choices,default=OpcionesGenero.MASCULINO)
    habilitado = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=ahora)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.nombre_lector} {self.rut_lector}'


class TipoCategoria(models.Model):
    tipo_categoria = models.CharField(max_length=50, null=False)
    habilitado = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=ahora)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.tipo_categoria


class Categoria(models.Model):
    id_tipo_categoria = models.ForeignKey(
        TipoCategoria, on_delete=models.CASCADE, null=False)
    categoria = models.CharField(max_length=100, null=False)
    descripcion = models.CharField(max_length=255, null=True)
    habilitado = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=ahora)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.categoria


class Libro(models.Model):
    id_biblioteca = models.ForeignKey(
        Biblioteca, on_delete=models.CASCADE, null=False)
    id_categoria = models.ForeignKey(
        Categoria, on_delete=models.CASCADE, null=True)
    id_autor = models.ForeignKey(Autor, on_delete=models.CASCADE, null=False)
    titulo = models.CharField(max_length=255, null=False)
    paginas = models.IntegerField(null=False)
    copias = models.IntegerField(null=False)
    ubicacion = models.CharField(max_length=255, null=False)
    fisico = models.BooleanField(default=True)
    habilitado = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=ahora)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titulo


class Prestamo(models.Model):
    id_libro = models.ForeignKey(Libro, on_delete=models.CASCADE, null=False)
    id_lector = models.ForeignKey(
        Lector, on_delete=models.CASCADE, null=False)
    fecha_prestamo = models.DateTimeField(auto_now_add=True)
    fecha_devolucion = models.DateField(null=True)
    fecha_retorno = models.DateTimeField(null=True)


class Reserva(models.Model):
    class TipoReservaChoices(models.IntegerChoices):
        NO_RESERVA = 0, 'Sin Reserva'
        SEMANA = 1, '1 Semana'
        MES = 2, '1 Mes'
        SEMESTRE = 3, '1 Semestre'
    id_libro = models.ForeignKey(Libro, on_delete=models.CASCADE, null=False)
    id_lector = models.ForeignKey(
        Lector, on_delete=models.CASCADE, null=False)
    fecha_reserva = models.DateTimeField(auto_now_add=True)
    tipo_reserva = models.IntegerField(choices=TipoReservaChoices.choices,default=TipoReservaChoices.NO_RESERVA)
    habilitado = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=ahora)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id_lector} {self.id_libro} {self.fecha_reserva}'


class TipoParametro(models.Model):
    tipo_parametro = models.CharField(max_length=50, null=False)
    habilitado = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=ahora)
    updated_at = models.DateTimeField(auto_now=True)


class Parametro(models.Model):
    id_tipo_parametro = models.ForeignKey(
        TipoParametro, on_delete=models.CASCADE, null=False)
    clave_parametro = models.CharField(max_length=100, null=False)
    valor_parametro = models.CharField(max_length=255, null=True)
    habilitado = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=ahora)
    updated_at = models.DateTimeField(auto_now=True)

biblioteca/forms.py
from django import forms
from .models import Nacionalidad

class NacionalidadForm(forms.ModelForm):
    class Meta:
        model = Nacionalidad
        fields = ['pais', 'nacionalidad']

    pais = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    nacionalidad = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

biblioteca/templates/biblioteca/inicio.html
{% extends "plantilla_base.html" %} {% block content %} {% load iconic %}
<div class="container">
  <div class="row">
    <figure>
      <blockquote class="blockquote">
        <p class="mb-0">
          Hay más tesoros en los libros que en todo el botín de los piratas de
          la Isla del Tesoro.
        </p>
      </blockquote>
      <figcaption class="blockquote-footer">
        Walt Disney (1901-1966)
        <cite title="Source Title"
          >Productor, director y guionista estadounidense.</cite
        >
      </figcaption>
    </figure>
  </div>
</div>

{% comment %} {% for field in permisos %}
  <div class="col-4">
    {{ field }}
  </div>
{% endfor %} {% endcomment %}

<div class="row iconos">
  <div class="row container d-flex justify-content-center">
    <div class="col-4 d-flex justify-content-center" style="margin: auto">
      <a class="text-decoration-none" href="biblioteca/bibliotecas/">
        <div
          class="card text-white bg-dark mb-3 text-center"
          style="max-width: 20rem"
        >
          <div class="card-header">{% iconic_icon "bank" size=50 %}</div>
          <div class="card-body">
            <h4 class="card-title">Gestión de</br> Biblioteca</h4>
            <p class="card-text">
              Información general de la biblioteca actual.
            </p>
          </div>
          <div class="card-footer text-muted"></div>
        </div>
      </a>
    </div>

    <div class="col-4 d-flex justify-content-center">
      <a class="text-decoration-none" href="/listado_autores">
        <div
          class="card text-white bg-dark mb-3 text-center"
          style="max-width: 20rem"
        >
          <div class="card-header">{% iconic_icon "user" size=50 %}</div>
          <div class="card-body">
            <h4 class="card-title">Gestión de</br> Autores</h4>
            <p class="card-text">
              Gestione completamente los autores de las obras de la Biblioteca.
            </p>
          </div>
          <div class="card-footer text-muted"></div>
        </div>
      </a>
    </div>

    <div class="col-4 d-flex justify-content-center">
      <a class="text-decoration-none" href="/listado_libros">
        <div
          class="card text-white bg-dark mb-3 text-center"
          style="max-width: 20rem"
        >
          <div class="card-header">{% iconic_icon "book" size=50 %}</div>
          <div class="card-body">
            <h4 class="card-title">Gestión de</br> Libros</h4>
            <p class="card-text">
              Control de libros y recursos varios de la biblioteca.
            </p>
          </div>
          <div class="card-footer text-muted"></div>
        </div>
      </a>
    </div>
  </div>

  <div class="row container d-flex justify-content-center">
    <div class="col-4 d-flex justify-content-center">
      <a class="text-decoration-none" href="/listado_lectores">
        <div
          class="card text-white bg-dark mb-3 text-center"
          style="max-width: 20rem"
        >
          <div class="card-header">{% iconic_icon "users" size=50 %}</div>
          <div class="card-body">
            <h4 class="card-title">Gestión de</br> Lectores</h4>
            <p class="card-text">
              Crear, editar y gestionar el comportamiento de los lectores.
            </p>
          </div>
          <div class="card-footer text-muted"></div>
        </div>
      </a>
    </div>

    <div class="col-4 d-flex justify-content-center">
      <a class="text-decoration-none" href="biblioteca/reservas/">
        <div
          class="card text-white bg-dark mb-3 text-center"
          style="max-width: 20rem"
        >
          <div class="card-header">{% iconic_icon "share" size=50 %}</div>
          <div class="card-body">
            <h4 class="card-title">Reserva de</br> Libros</h4>
            <p class="card-text">
              Manejo de reservas de libros.
            </p>
          </div>
          <div class="card-footer text-muted"></div>
        </div>
      </a>
    </div>

    <div class="col-4 d-flex justify-content-center">
      <a class="text-decoration-none" href="/listado_comunas">
        <div
          class="card text-white bg-dark mb-3 text-center"
          style="max-width: 20rem"
        >
          <div class="card-header">{% iconic_icon "settings" size=50 %}</div>
          <div class="card-body">
            <h4 class="card-title">Configuración de</br> Sistema</h4>
            <p class="card-text">
              Configuración general del sistema y parámetros del sistema.
            </p>
          </div>
          <div class="card-footer text-muted"></div>
        </div>
      </a>
    </div>
  </div>
</div>
{% endblock %}

biblioteca/templates/biblioteca/lista_autores.html
{% extends 'plantilla_base.html' %} {% load static %} {% block title %}Listado
Autores{% endblock%} {% block cabecera %} {% endblock %} {% block content %}
<h1>Listado de Autores</h1>
<table id="tabla_autores" class="cell-border">
  <thead>
    <tr>
      <th>N°</th>
      <th>Nombre</th>
      <th>Pseudónimo</th>
      {% comment %} <th></th> {% endcomment %}
      {% comment %} <th>Nacionalidad</th> {% endcomment %}
      <th>Biografía</th>
    </tr>
  </thead>
  <tbody>
    {% for autor in autores %}
    <tr>
      <td>{{ autor.id }}</td>
      <td>{{ autor.nombre }}</td>
      <td>{{ autor.pseudonimo }}</td>
      {% comment %} <td><img src="{{ autor.imagen_autor }}" alt="{{ autor.nombre }}" width="100" height="100"></td> {% endcomment %}
      {% comment %} <td>{{ autor.id_nacionalidad }}</td> {% endcomment %}
      <td>{{ autor.biografia }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %} {% block scripts %}
<script
  type="text/javascript"
  src="{% static 'scripts/listados_datatables.js' %}"
></script>
{% endblock %}

biblioteca/templates/biblioteca/lista_comunas.html
{% extends 'plantilla_base.html' %} {% load static %} {% block title %}Listado
Lectores{% endblock%} {% block cabecera %} {% endblock %} {% block content %}
<h1>Listado de Comunas</h1>
<table id="tabla_comunas" class="display">
  <thead>
    <tr>
      <th>N°</th>
      <th>Código Comuna</th>
      <th>Nombre Comuna</th>
    </tr>
  </thead>
  <tbody>
    {% for comuna in comunas %}
    <tr>
      <td>{{ comuna.id }}</td>
      <td>{{ comuna.codigo_comuna }}</td>
      <td>{{ comuna.nombre_comuna }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %} {% block scripts %}
<script
  type="text/javascript"
  src="{% static 'scripts/listados_datatables.js' %}"
></script>
{% endblock %}

biblioteca/templates/biblioteca/lista_lectores.html
{% extends 'plantilla_base.html' %} {% load static %} {% block title %}Listado
Lectores{% endblock%} {% block cabecera %} {% endblock %} {% block content %}
<h1>Listado de Lectores</h1>
<table id="tabla_lectores" class="display">
  <thead>
    <tr>
      <th>RUT Lector</th>
      <th>Nombre Lector</th>
      <th>Correo Lector</th>
      <th>Fecha Nacimiento</th>
    </tr>
  </thead>
  <tbody>
    <!-- Data will be loaded dynamically or from Django context -->
  </tbody>
</table>
{% endblock %} {% block scripts %}
<script
  type="text/javascript"
  src="{% static 'scripts/listados_datatables.js' %}"
></script>
{% endblock %}

biblioteca/templates/biblioteca/lista_libros.html
{% extends 'plantilla_base.html' %} {% load static %} 

{% block title %}Listado Libros{% endblock%}
{% block estilos %}<link rel="stylesheet" href="{% static 'css/estilos_libros.css' %}" />{% endblock %}

{% block cabecera %}<h1>Listado de Libros</h1>{% endblock %} 

{% block content %}

{% load widget_tweaks %}

<div class="row">
    <form method="get">
        <div class="row">
            {% for field in filter.form %}
                <div class="col-4">
                    {{ field.label_tag }}
                    {% render_field field class="form-control" placeholder=field.label %}
                </div>
            {% endfor %}
        </div>
        </br>
        <button type="submit" class="btn btn-primary">Aplicar Filtros</button>
    </form>
</div>
</br>

<div class="row">
    {% for obj in filter.qs %}
        <div class="col-sm-4 tarjeta-libro">
            <div class="card">
                <div class="card-header">{{obj.titulo}}</div>
                <div class="card-body">
                    <input type="hidden" value="{{obj.id_categoria}}">
                    <h5 class="card-title">{{obj.id_autor}}</h5>
                    <p class="card-text">Categoría: {{obj.id_categoria}}</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'scripts/scripts_libros.js' %}"></script>
{% endblock %}

biblioteca/templates/biblioteca/nacionalidad_form.html
{% extends 'plantilla_base.html' %} {% load static %}{% load iconic %} {% block title %}Agregar
Nacionalidad{% endblock%} {% block estilos %}<link rel="stylesheet" href="{% static 'css/estilos_libros.css' %}"/>
{% endblock %} {% block cabecera %}
<h1>Agregar Nacionalidad</h1>
{% endblock %} {% block content %}   
<form method="post">{% csrf_token %}
    <div class="row">

        {% for field in form %}
    <div class="col">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
{% endfor %}
    </div>
</br>
    <input type="submit" value="Guardar" class="btn btn-primary">
</form>
{% endblock %} {% block scripts %}
    {% comment %} <script type="text/javascript" src="{% static 'scripts/scripts_biblioteca.js' %}"></script> {% endcomment %}
{% endblock %}

biblioteca/templates/biblioteca/nacionalidad_list.html
{% extends 'plantilla_base.html' %} {% load static %}{% load iconic %} {% block title %}Listado
Nacionalidades{% endblock%} {% block estilos %}<link rel="stylesheet" href="{% static 'css/estilos_libros.css' %}"
/>{% endblock %} {% block cabecera %}
<h1>Listado de Nacionalidades</h1>
{% endblock %} {% block content %}   
    <table id="tabla_nacionalidades" class="table table-striped table-hover" data-pagination="true" data-search="true">
        <thead>
            <tr>
                <th>N°</th>
                <th>País</th>
                <th>Nacionalidad</th>
                <th>Opciones</th>
            </tr>
        </thead>
    
        <tbody>
            {% for nacionalidad in object_list %}
                <td>{{ nacionalidad.id }}</td>
                <td>{{ nacionalidad.pais }}</td>
                <td>{{ nacionalidad.nacionalidad }}</td>
                <td>
                    <a class="text-decoration-none" href="#">{% iconic_icon "eye" %}</a>
                    {% if perms.biblioteca.add_nacionalidad or perms.biblioteca.change_nacionalidad %}
                        <a class="text-decoration-none" href="#">{% iconic_icon "edit" %}</a>
                        <a class="text-decoration-none" href="#">{% iconic_icon "trash" %}</a>
                    {% endif %}
                </td>
            <!-- Data will be loaded dynamically or from Django context -->
        </tbody>
        {% empty %}
            <h3>No hay data de Nacionalidades.</h3>
        {% endfor %}
    </table>
{% endblock %} {% block scripts %}
{% comment %} <script type="text/javascript" src="{% static 'scripts/listados_datatables.js' %}"></script> {% endcomment %}
{% endblock %}